# Generated by Django 3.1.2 on 2020-10-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mems_apps', '0003_auto_20201003_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='food_name',
            field=models.CharField(default='food_name', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
