# Generated by Django 3.1.2 on 2020-10-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mems_apps', '0004_auto_20201003_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
