# Generated by Django 3.1.2 on 2020-10-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mems_apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messextra',
            name='quantity',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
